[package]
name = "rust-gpu-cli-builder"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.21", features = ["derive"] }
spirv-builder = "0.9.0"

[workspace]
